name: Publish NuGet Package to GitHub Packages

on:
  push:
    branches:
      - main   # または任意のブランチ名

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        token: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKENで認証

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Pack project
      run: dotnet pack --configuration Release --no-build

    - name: Push NuGet package
      run: dotnet nuget push "**/bin/Release/*.nupkg" --source "github" --skip-duplicate