name: Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  status-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MyNugetPackage/MyNugetPackage.csproj

    - name: Build project
      run: dotnet build MyNugetPackage/MyNugetPackage.csproj --configuration Release --no-restore